/** Minimal Chrome extension types (full defs from `@types/chrome` after `npm install`) */
declare namespace chrome {
  namespace cookies {
    interface Cookie {
      name: string;
      value: string;
      domain: string;
      path: string;
    }
    function getAll(details: { domain?: string }): Promise<Cookie[]>;
  }
  namespace runtime {
    interface InstalledDetails {
      reason: string;
    }
    const onInstalled: {
      addListener(callback: (details: InstalledDetails) => void): void;
    };
  }
  namespace sidePanel {
    function setPanelBehavior(details: {
      openPanelOnActionClick: boolean;
    }): Promise<void>;
  }
  namespace runtime {
    function getURL(path: string): string;
  }
  namespace tabs {
    function create(props: { url: string; active?: boolean }): Promise<{ id?: number }>;
  }
}

/** WXT auto-import (normally generated by `wxt prepare` into `.wxt/`) */
type BackgroundDefinition = {
  main: () => void;
  type: 'background';
};

declare function defineBackground(main: () => void): BackgroundDefinition;
declare function defineBackground(definition: BackgroundDefinition): BackgroundDefinition;

interface ImportMetaEnv {
  readonly MANIFEST_VERSION: 2 | 3;
  readonly BROWSER: string;
  readonly CHROME: boolean;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
