/** Minimal Chrome extension types (full defs from `@types/chrome` after `npm install`) */
declare namespace chrome {
  namespace cookies {
    interface Cookie {
      name: string;
      value: string;
      domain: string;
      path: string;
    }
    function getAll(details: { domain?: string; url?: string }): Promise<Cookie[]>;
  }
  namespace runtime {
    interface InstalledDetails {
      reason: string;
    }
    const onInstalled: {
      addListener(callback: (details: InstalledDetails) => void): void;
    };
    function getURL(path: string): string;
    type RuntimeMessageListener = (
      message: { type?: string },
      sender?: unknown,
      sendResponse?: (response?: unknown) => void,
    ) => void | boolean;
    const onMessage: {
      addListener(callback: RuntimeMessageListener): void;
      removeListener(callback: RuntimeMessageListener): void;
    };
    function sendMessage(message: { type: string }): Promise<void>;
  }
  namespace sidePanel {
    function setPanelBehavior(details: {
      openPanelOnActionClick: boolean;
    }): Promise<void>;
  }
  namespace tabs {
    function create(props: { url: string; active?: boolean }): Promise<{ id?: number }>;
    function query(queryInfo: {
      url?: string | string[];
    }): Promise<Array<{ id?: number; url?: string }>>;
    const onUpdated: {
      addListener(
        callback: (
          tabId: number,
          changeInfo: { status?: string },
          tab: { url?: string },
        ) => void,
      ): void;
    };
  }
  namespace scripting {
    function executeScript(injection: {
      target: { tabId: number };
      func: (...args: unknown[]) => unknown;
      args?: unknown[];
    }): Promise<Array<{ result?: unknown }>>;
  }
}

/** WXT auto-import (normally generated by `wxt prepare` into `.wxt/`) */
type BackgroundDefinition = {
  main: () => void;
  type: 'background';
};

declare function defineBackground(main: () => void): BackgroundDefinition;
declare function defineBackground(definition: BackgroundDefinition): BackgroundDefinition;

interface ImportMetaEnv {
  readonly MANIFEST_VERSION: 2 | 3;
  readonly BROWSER: string;
  readonly CHROME: boolean;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

declare module '*?url' {
  const url: string;
  export default url;
}
